-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES Table (Sync with Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  name text,
  role text default 'student', -- 'student', 'admin', 'assistant'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. LECTURES Table
create table public.lectures (
  id uuid default uuid_generate_v4() primary key,
  title text not null,
  section text not null, -- e.g., '수학I정규', '2026겨울특강'
  youtube_link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. NOTICES Table
create table public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  author text default '관리자',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. QUESTIONS Table
create table public.questions (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  author text,
  user_id uuid references auth.users,
  status text default 'pending', -- 'pending', 'answered'
  answer text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Enable RLS (Row Level Security) - Optional but recommended
alter table public.profiles enable row level security;
alter table public.lectures enable row level security;
alter table public.notices enable row level security;
alter table public.questions enable row level security;

-- 6. RLS Policies (Simple Public Read / Admin Write)

-- Lectures: Everyone can read, Only Admin can insert/update
create policy "Public lectures are viewable by everyone" on public.lectures for select using (true);
create policy "Admins can insert lectures" on public.lectures for insert with check (auth.uid() in (select id from public.profiles where role = 'admin'));

-- Notices: Everyone can read
create policy "Public notices are viewable by everyone" on public.notices for select using (true);

-- Questions: Everyone can read titles, Users can insert
create policy "Questions are viewable by everyone" on public.questions for select using (true);
create policy "Users can insert questions" on public.questions for insert with check (auth.uid() = user_id);

-- Profiles: Users can see their own profile
create policy "Users can see own profile" on public.profiles for select using (auth.uid() = id);

-- Handle New User Trigger (Automatically create profile on signup)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, name, role)
  values (new.id, new.email, new.raw_user_meta_data->>'name', coalesce(new.raw_user_meta_data->>'role', 'student'));
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
